version: '3.8'

services:
  apiservidores-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: apiservidores-app
    volumes:
      - .:/var/www
    networks:
      - laravel

networks:
  laravel:
    external: true
